Final Capstone Project
lfmnovaes/car-rental-back-end pull request #14
Opened 2022-03-01 19:41 UTC by lfmnovaes

2022-03-01 20:04 UTC, MuriloRoque requested changes
Hi @lfmnovaes, @elassis, @ramiaquista,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!

## Suggested changes
_Check the comments under the review._

You can also consider:

- [ ] I suggest adding some tests.

## Highlights

- Very professional repository.
- Your code is clean.

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-03-01 20:04 UTC, MuriloRoque commented on app/controllers/api/users_controller.rb
> +    render json: @user
- [x] I know you are still not finished and this could be just something your front-end is doing for testing right now (I haven't checked it yet), but I wouldn't leave this action like this. You are selecting the users where the name is equal to the id, and this doesn't make sense for me, unless I'm missing something. The top two lines that are commented make a lot more sense.

2022-03-01 20:04 UTC, MuriloRoque commented on app/models/car.rb
> +end
- [x] I would add some validation to the models.

2022-03-01 20:04 UTC, MuriloRoque commented on app/models/city.rb
> +end
- [x] I would add some validation to the models.

2022-03-01 20:04 UTC, MuriloRoque commented on app/models/reservation.rb
> +end
- [x] I would add some validation to the models.

2022-03-01 20:04 UTC, MuriloRoque commented on app/models/user.rb
> +end
- [x] I would add some validation to the models.

2022-03-02 18:30 UTC, ramiaquista commented
#### Thank @MuriloRoque for the amazing review! We have implemented new features, the requested changes and more styling to the app! 😄

2022-03-02 18:38 UTC, MuriloRoque approved these changes
Hi @ramiaquista, @lfmnovaes, @elassis,

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2022-03-03 16:17 UTC, merged